(function () {
    const EVENTOS_COMPLETOS = [
        {
            id: 'ia_revolucion',
            titulo: '🚀 Revolución de la inteligencia artificial',
            subtitulo: 'Una nueva generación de chips reduce drásticamente los costos de IA.',
            descripcion: 'Una nueva generación de chips permite reducir significativamente el costo de operar sistemas avanzados de inteligencia artificial.',
            categoria: 'boom',
            rareza: 'raro',
            intensidad: 'alta',
            duracion: 150,
            cooldown: 300,
            probabilidad: 4,
            sectoresBeneficiados: ['IA', 'semiconductores', 'tecnologia', 'centros_datos'],
            sectoresPerjudicados: ['tecnologia_legacy'],
            impactosSectores: { IA: 14, semiconductores: 11, tecnologia: 9, centros_datos: 10, software: 7, tecnologia_legacy: -4 },
            materiasPrimas: { cobre: 5, electricidad: 7 },
            empresas: { beneficiadas: [], perjudicadas: [] },
            bancos: { efecto: 'aumentan financiación tecnológica', tasa: -3, aprobacion: 6, limite: 8 },
            creditos: { disponibles: ['investigacion', 'expansion'], modificadores: { investigacion: -8, expansion: -3 } },
            liquidez: 3,
            volatilidad: 8,
            confianza: 9,
            efectosSecundarios: ['aumenta_demanda_chips', 'aumenta_demanda_energia', 'acelera_inversion_tecnologica'],
            condiciones: ['si_demanda_chips_alta_aumentar_escasez'],
            eventosRelacionados: ['escasez_semiconductores', 'expansion_centros_datos'],
            noticia: 'Una nueva generación de chips permite reducir significativamente el costo de operar sistemas avanzados de inteligencia artificial.',
            alerta: '🚀 El sector tecnológico entra en una nueva fase de expansión.',
            etiquetas: ['IA', 'chips', 'tecnologia', 'inversion']
        },
        {
            id: 'transicion_energetica',
            titulo: '⚡ Transición energética',
            subtitulo: 'La inversión mundial en energía renovable acelera.',
            descripcion: 'Grandes productores anuncian inversiones masivas en parques eólicos y solares.',
            categoria: 'boom',
            rareza: 'poco_comun',
            intensidad: 'alta',
            duracion: 130,
            cooldown: 280,
            probabilidad: 6,
            sectoresBeneficiados: ['renovables', 'construccion', 'ingenieria', 'mineria', 'energia'],
            sectoresPerjudicados: ['petroleo'],
            impactosSectores: { renovables: 14, construccion: 9, ingenieria: 8, mineria: 6, energia: 7, petroleo: -5 },
            materiasPrimas: { cobre: 8, litio: 6 },
            empresas: { beneficiadas: [], perjudicadas: [] },
            bancos: { efecto: 'favorecen proyectos verdes', tasa: -4, aprobacion: 8, limite: 10 },
            creditos: { disponibles: ['expansion', 'investigacion'], modificadores: { expansion: -5, investigacion: -3 } },
            liquidez: 2,
            volatilidad: 7,
            confianza: 8,
            efectosSecundarios: ['aumenta_demanda_cobre', 'aumenta_demanda_componentes'],
            eventosRelacionados: ['escasez_cobre', 'boom_infraestructura'],
            noticia: 'Grandes productores energéticos anuncian contratos para desarrollar nuevos parques renovables.',
            alerta: '⚡ El mercado incorpora una nueva oleada de inversión verde.',
            etiquetas: ['energia', 'renovables', 'infraestructura']
        },
        {
            id: 'avance_medico',
            titulo: '🧪 Avance médico histórico',
            subtitulo: 'Un nuevo tratamiento supera las expectativas iniciales.',
            descripcion: 'Investigadores anuncian resultados extraordinarios en una nueva generación de tratamientos.',
            categoria: 'boom',
            rareza: 'raro',
            intensidad: 'alta',
            duracion: 120,
            cooldown: 260,
            probabilidad: 3,
            sectoresBeneficiados: ['salud', 'farmaceutica', 'biotecnologia', 'laboratorios'],
            sectoresPerjudicados: [],
            impactosSectores: { salud: 9, farmaceutica: 14, biotecnologia: 17, laboratorios: 11 },
            bancos: { efecto: 'aumentan financiación científica', tasa: -3, aprobacion: 5, limite: 7 },
            creditos: { disponibles: ['investigacion'], modificadores: { investigacion: -10 } },
            liquidez: 2,
            volatilidad: 10,
            confianza: 7,
            efectosSecundarios: ['aumenta_inversion_biotecnologia', 'aumenta_valor_empresas_innovadoras'],
            noticia: 'Investigadores anuncian resultados extraordinarios en una nueva generación de tratamientos.',
            alerta: '🧪 La innovación médica acelera la confianza del mercado.',
            etiquetas: ['salud', 'farmaceutica', 'biotecnologia']
        },
        {
            id: 'litio_estrategico',
            titulo: '💎 Litio estratégico',
            subtitulo: 'Se descubre un enorme yacimiento de litio.',
            descripcion: 'Un yacimiento de enorme importancia estratégica podría transformar el mercado mundial de baterías.',
            categoria: 'materias_primas',
            rareza: 'epico',
            intensidad: 'extrema',
            duracion: 180,
            cooldown: 500,
            probabilidad: 1.5,
            sectoresBeneficiados: ['mineria', 'baterias', 'automoviles_electricos', 'energia'],
            sectoresPerjudicados: [],
            impactosSectores: { mineria: 12, baterias: 9, automoviles_electricos: 8, energia: 5 },
            materiasPrimas: { litio: 22, cobre: 4 },
            bancos: { efecto: 'aumentan financiación minera', tasa: -2, aprobacion: 5, limite: 12 },
            creditos: { disponibles: ['adquisicion', 'expansion'], modificadores: { adquisicion: -3, expansion: -5 } },
            liquidez: 5,
            volatilidad: 14,
            confianza: 8,
            efectosSecundarios: ['aumenta_oferta_futura_litio', 'aumenta_inversion_mineria'],
            eventosRelacionados: ['boom_autos_electricos', 'exceso_oferta_litio'],
            noticia: 'Un yacimiento de enorme importancia estratégica podría transformar el mercado mundial de baterías.',
            alerta: '💎 El litio vuelve a ser un activo de máxima relevancia.',
            etiquetas: ['litio', 'minerias', 'baterias']
        },
        {
            id: 'infraestructura_verde',
            titulo: '🏗️ Infraestructura verde',
            subtitulo: 'Comienza un gigantesco programa de construcción sostenible.',
            descripcion: 'Se anuncia un programa de infraestructura sostenible de gran escala.',
            categoria: 'boom',
            rareza: 'poco_comun',
            intensidad: 'alta',
            duracion: 140,
            cooldown: 300,
            probabilidad: 5,
            sectoresBeneficiados: ['construccion', 'ingenieria', 'renovables', 'materiales', 'transporte'],
            sectoresPerjudicados: [],
            impactosSectores: { construccion: 13, ingenieria: 10, renovables: 11, materiales: 7, transporte: 5 },
            materiasPrimas: { cobre: 7, acero: 6, cemento: 5 },
            bancos: { efecto: 'financian proyectos de infraestructura', tasa: -4, aprobacion: 7, limite: 10 },
            creditos: { disponibles: ['expansion'], modificadores: { expansion: -6 } },
            liquidez: 3,
            volatilidad: 6,
            confianza: 8,
            noticia: 'Se anuncia un programa de infraestructura sostenible de gran escala.',
            alerta: '🏗️ La construcción verde abre una nueva ola de oportunidades.',
            etiquetas: ['construccion', 'renovables', 'infraestructura']
        },
        {
            id: 'nueva_red_telecom',
            titulo: '🛰️ Nueva generación de telecomunicaciones',
            subtitulo: 'Los primeros pilotos superan las expectativas.',
            descripcion: 'Los operadores anuncian que las primeras pruebas de la nueva generación de redes superaron las expectativas.',
            categoria: 'tecnologia',
            rareza: 'raro',
            intensidad: 'alta',
            duracion: 120,
            cooldown: 280,
            probabilidad: 3,
            sectoresBeneficiados: ['telecomunicaciones', 'semiconductores', 'tecnologia', 'infraestructura_digital'],
            sectoresPerjudicados: [],
            impactosSectores: { telecomunicaciones: 13, semiconductores: 8, tecnologia: 9, infraestructura_digital: 11 },
            materiasPrimas: { cobre: 5 },
            bancos: { efecto: 'financian infraestructura digital', tasa: -2, aprobacion: 5, limite: 8 },
            creditos: { disponibles: ['expansion', 'investigacion'], modificadores: { expansion: -3, investigacion: -5 } },
            liquidez: 2,
            volatilidad: 9,
            confianza: 7,
            noticia: 'Los operadores anuncian que las primeras pruebas de la nueva generación de redes superaron las expectativas.',
            alerta: '🛰️ La infraestructura digital entra en una nueva fase.',
            etiquetas: ['telecomunicaciones', '5g', 'infraestructura']
        },
        {
            id: 'boom_autos_electricos',
            titulo: '🚗 Boom de vehículos eléctricos',
            subtitulo: 'Un fabricante anuncia producción masiva de modelos económicos.',
            descripcion: 'Un fabricante sorprende al mercado anunciando producción masiva de vehículos eléctricos económicos.',
            categoria: 'boom',
            rareza: 'poco_comun',
            intensidad: 'extrema',
            duracion: 150,
            cooldown: 320,
            probabilidad: 5,
            sectoresBeneficiados: ['automoviles_electricos', 'baterias', 'mineria', 'transporte'],
            sectoresPerjudicados: ['petroleo', 'combustibles'],
            impactosSectores: { automoviles_electricos: 14, baterias: 11, mineria: 7, transporte: 5, petroleo: -6, combustibles: -5 },
            materiasPrimas: { litio: 14, cobre: 7, niquel: 8 },
            bancos: { efecto: 'favorecen financiación automotriz', tasa: -2, aprobacion: 5, limite: 7 },
            creditos: { disponibles: ['expansion', 'adquisicion'], modificadores: { expansion: -4, adquisicion: -2 } },
            liquidez: 4,
            volatilidad: 12,
            confianza: 9,
            efectosSecundarios: ['aumenta_demanda_litio', 'aumenta_demanda_baterias', 'reduce_demanda_petroleo'],
            eventosRelacionados: ['escasez_litio', 'escasez_semiconductores'],
            noticia: 'Un fabricante sorprende al mercado anunciando producción masiva de vehículos eléctricos económicos.',
            alerta: '🚗 El mercado automotriz eléctrico entra en una etapa de expansión acelerada.',
            etiquetas: ['automoviles', 'electricos', 'litio']
        },
        {
            id: 'boom_comercio',
            titulo: '🛒 Temporada récord',
            subtitulo: 'Las ventas digitales superan todas las previsiones.',
            descripcion: 'Las ventas online superan las previsiones y obligan a las empresas logísticas a ampliar operaciones.',
            categoria: 'boom',
            rareza: 'comun',
            intensidad: 'alta',
            duracion: 100,
            cooldown: 220,
            probabilidad: 10,
            sectoresBeneficiados: ['comercio', 'ecommerce', 'logistica', 'transporte', 'consumo'],
            sectoresPerjudicados: [],
            impactosSectores: { comercio: 12, ecommerce: 14, logistica: 10, transporte: 6, consumo: 8 },
            bancos: { efecto: 'aumentan créditos comerciales', tasa: -2, aprobacion: 6, limite: 6 },
            creditos: { disponibles: ['expansion'], modificadores: { expansion: -3 } },
            liquidez: 4,
            volatilidad: 6,
            confianza: 8,
            noticia: 'Las ventas online superan las previsiones y obligan a las empresas logísticas a ampliar operaciones.',
            alerta: '🛒 Comercio digital y logística marcan un nuevo máximo.',
            etiquetas: ['retail', 'ecommerce', 'logistica']
        },
        {
            id: 'tasas_bajas',
            titulo: '🏦 Tasas en baja',
            subtitulo: 'El crédito se vuelve temporalmente más accesible.',
            descripcion: 'Las condiciones de financiación mejoran y los bancos ofrecen crédito más barato.',
            categoria: 'financiero',
            rareza: 'comun',
            intensidad: 'alta',
            duracion: 160,
            cooldown: 350,
            probabilidad: 8,
            sectoresBeneficiados: ['inmobiliario', 'construccion', 'consumo', 'empresas', 'finanzas'],
            sectoresPerjudicados: [],
            impactosSectores: { inmobiliario: 10, construccion: 8, consumo: 7, empresas: 6, finanzas: 5 },
            bancos: { efecto: 'aumentan colocación de créditos', tasa: -10, aprobacion: 12, limite: 10 },
            creditos: { disponibles: ['puente', 'expansion', 'adquisicion', 'refinanciacion'], modificadores: { puente: -5, expansion: -7, adquisicion: -5, refinanciacion: -8 } },
            liquidez: 6,
            volatilidad: 4,
            confianza: 10,
            noticia: 'Las condiciones de financiación mejoran y los bancos comienzan a ofrecer crédito más barato.',
            alerta: '🏦 La financiación vuelve a estar más disponible.',
            etiquetas: ['bancos', 'crédito', 'inmobiliario']
        },
        {
            id: 'boom_turismo',
            titulo: '✈️ Turismo internacional en auge',
            subtitulo: 'Las reservas internacionales superan las previsiones.',
            descripcion: 'La demanda internacional de viajes crece con fuerza y las empresas turísticas amplían su capacidad.',
            categoria: 'boom',
            rareza: 'comun',
            intensidad: 'alta',
            duracion: 110,
            cooldown: 240,
            probabilidad: 9,
            sectoresBeneficiados: ['turismo', 'hoteles', 'aerolineas', 'restaurantes', 'transporte'],
            sectoresPerjudicados: [],
            impactosSectores: { turismo: 14, hoteles: 12, aerolineas: 9, restaurantes: 7, transporte: 6 },
            liquidez: 4,
            volatilidad: 7,
            confianza: 9,
            noticia: 'La demanda internacional de viajes crece con fuerza y las empresas turísticas amplían su capacidad.',
            alerta: '✈️ El turismo vuelve a ser un motor de crecimiento.',
            etiquetas: ['turismo', 'hoteles', 'vacaciones']
        },
        {
            id: 'avance_energia',
            titulo: '⚡ Avance en energía limpia',
            subtitulo: 'Una nueva tecnología mejora el almacenamiento energético.',
            descripcion: 'Una nueva tecnología energética promete almacenar electricidad de forma más eficiente.',
            categoria: 'tecnologia',
            rareza: 'epico',
            intensidad: 'extrema',
            duracion: 170,
            cooldown: 500,
            probabilidad: 1.5,
            sectoresBeneficiados: ['renovables', 'baterias', 'energia', 'automoviles_electricos'],
            sectoresPerjudicados: ['petroleo'],
            impactosSectores: { renovables: 18, baterias: 16, energia: 11, automoviles_electricos: 9, petroleo: -7 },
            materiasPrimas: { litio: 10, cobre: 8 },
            liquidez: 5,
            volatilidad: 16,
            confianza: 12,
            eventosRelacionados: ['boom_autos_electricos', 'transicion_energetica'],
            noticia: 'Una nueva tecnología energética promete almacenar electricidad de forma más eficiente.',
            alerta: '⚡ La energía limpia recibe un impulso tecnológico clave.',
            etiquetas: ['energia', 'baterias', 'tecnologia']
        },
        {
            id: 'tratado_comercial',
            titulo: '🌍 Nuevo tratado comercial',
            subtitulo: 'Varios mercados reducen barreras al comercio.',
            descripcion: 'Un nuevo acuerdo comercial reduce las barreras entre importantes mercados internacionales.',
            categoria: 'geopolitico',
            rareza: 'poco_comun',
            intensidad: 'alta',
            duracion: 130,
            cooldown: 300,
            probabilidad: 6,
            sectoresBeneficiados: ['comercio', 'transporte', 'logistica', 'industria', 'exportadores'],
            sectoresPerjudicados: [],
            impactosSectores: { comercio: 10, transporte: 7, logistica: 9, industria: 7, exportadores: 11 },
            liquidez: 5,
            volatilidad: -5,
            confianza: 10,
            noticia: 'Un nuevo acuerdo comercial reduce las barreras entre importantes mercados internacionales.',
            alerta: '🌍 El comercio internacional recibe un nuevo impulso.',
            etiquetas: ['comercio', 'global', 'tratados']
        },
        {
            id: 'correccion_tecnologica',
            titulo: '📉 Corrección tecnológica',
            subtitulo: 'Los inversores cuestionan las valoraciones del sector.',
            descripcion: 'Las ventas se aceleran después de que inversores consideren excesivas algunas valoraciones tecnológicas.',
            categoria: 'crisis',
            rareza: 'comun',
            intensidad: 'alta',
            duracion: 120,
            cooldown: 280,
            probabilidad: 8,
            sectoresBeneficiados: [],
            sectoresPerjudicados: ['tecnologia', 'IA', 'semiconductores', 'software'],
            impactosSectores: { tecnologia: -9, IA: -11, semiconductores: -7, software: -6 },
            liquidez: -5,
            volatilidad: 14,
            confianza: -9,
            creditos: { disponibles: ['refinanciacion'], modificadores: { refinanciacion: 5 } },
            noticia: 'Las ventas se aceleran después de que inversores consideren excesivas algunas valoraciones tecnológicas.',
            alerta: '📉 La tecnología se corrige y los precios responden.',
            etiquetas: ['tecnologia', 'correccion', 'IA']
        },
        {
            id: 'inflacion_elevada',
            titulo: '📈 Inflación elevada',
            subtitulo: 'Los consumidores reducen el gasto.',
            descripcion: 'La inflación aumenta y los hogares comienzan a reducir sus gastos.',
            categoria: 'crisis',
            rareza: 'comun',
            intensidad: 'alta',
            duracion: 150,
            cooldown: 320,
            probabilidad: 8,
            sectoresBeneficiados: ['materias_primas_ajustadas'],
            sectoresPerjudicados: ['consumo', 'comercio', 'retail', 'construccion', 'empresas'],
            impactosSectores: { consumo: -8, comercio: -7, retail: -7, construccion: -5, empresas: -4 },
            materiasPrimas: { alimentos: 7, energia: 6 },
            bancos: { efecto: 'endurecen condiciones', tasa: 7, aprobacion: -8, limite: -7 },
            liquidez: -8,
            volatilidad: 12,
            confianza: -8,
            noticia: 'La inflación aumenta y los hogares comienzan a reducir sus gastos.',
            alerta: '📈 Los precios se endurecen y el consumo se frena.',
            etiquetas: ['inflacion', 'consumo', 'precios']
        },
        {
            id: 'brote_sanitario',
            titulo: '☣️ Brote sanitario',
            subtitulo: 'Las reservas turísticas y actividades presenciales caen.',
            descripcion: 'Las empresas turísticas registran cancelaciones mientras aumenta la demanda de servicios sanitarios.',
            categoria: 'crisis',
            rareza: 'raro',
            intensidad: 'extrema',
            duracion: 180,
            cooldown: 600,
            probabilidad: 2,
            sectoresBeneficiados: ['salud', 'farmaceutica', 'comercio_digital'],
            sectoresPerjudicados: ['turismo', 'hoteles', 'aerolineas', 'restaurantes'],
            impactosSectores: { turismo: -15, hoteles: -14, aerolineas: -12, restaurantes: -9, salud: 10, farmaceutica: 8, comercio_digital: 9 },
            bancos: { efecto: 'aumentan evaluación de riesgo', tasa: 5, aprobacion: -7, limite: -8 },
            liquidez: -10,
            volatilidad: 18,
            confianza: -15,
            noticia: 'Las empresas turísticas registran cancelaciones mientras aumenta la demanda de servicios sanitarios.',
            alerta: '☣️ El sector turístico sufre un golpe fuerte y la salud gana peso.',
            etiquetas: ['salud', 'turismo', 'sanitario']
        },
        {
            id: 'huelga_minera',
            titulo: '⛏️ Huelga minera',
            subtitulo: 'La producción de minerales estratégicos se reduce.',
            descripcion: 'Una huelga reduce la producción minera y presiona los precios de materias primas.',
            categoria: 'crisis',
            rareza: 'poco_comun',
            intensidad: 'alta',
            duracion: 120,
            cooldown: 300,
            probabilidad: 5,
            sectoresBeneficiados: [],
            sectoresPerjudicados: ['mineria', 'automoviles', 'baterias', 'construccion'],
            impactosSectores: { mineria: -9, automoviles: -5, baterias: -7, construccion: -5 },
            materiasPrimas: { cobre: 13, litio: 12, niquel: 10 },
            liquidez: -3,
            volatilidad: 13,
            confianza: -6,
            eventosRelacionados: ['escasez_semiconductores', 'boom_autos_electricos'],
            noticia: 'Una huelga reduce la producción minera y presiona los precios de materias primas.',
            alerta: '⛏️ La minería estratégica entra en una fase de presión.',
            etiquetas: ['mineria', 'litio', 'materias_primas']
        },
        {
            id: 'regulacion_ia',
            titulo: '⚖️ Nuevas reglas para la inteligencia artificial',
            subtitulo: 'Los reguladores introducen nuevos requisitos.',
            descripcion: 'Nuevos requisitos regulatorios obligan a las empresas de IA a modificar sus planes de expansión.',
            categoria: 'regulacion',
            rareza: 'poco_comun',
            intensidad: 'alta',
            duracion: 140,
            cooldown: 320,
            probabilidad: 5,
            sectoresBeneficiados: ['ciberseguridad', 'consultoria'],
            sectoresPerjudicados: ['IA', 'tecnologia', 'software'],
            impactosSectores: { IA: -10, tecnologia: -6, software: -5, ciberseguridad: 7, consultoria: 5 },
            bancos: { efecto: 'aumentan evaluación de empresas tecnológicas', tasa: 3, aprobacion: -5, limite: -4 },
            liquidez: -3,
            volatilidad: 12,
            confianza: -7,
            noticia: 'Nuevos requisitos regulatorios obligan a las empresas de IA a modificar sus planes de expansión.',
            alerta: '⚖️ La regulación tecnológica entra en una fase estricta.',
            etiquetas: ['IA', 'regulacion', 'tecnologia']
        },
        {
            id: 'escasez_materiales',
            titulo: '🧱 Escasez de materiales',
            subtitulo: 'Los retrasos afectan a proyectos de construcción.',
            descripcion: 'Los retrasos de suministro provocan un fuerte aumento en el precio de materiales.',
            categoria: 'crisis',
            rareza: 'comun',
            intensidad: 'alta',
            duracion: 110,
            cooldown: 240,
            probabilidad: 9,
            sectoresBeneficiados: [],
            sectoresPerjudicados: ['construccion', 'infraestructura', 'inmobiliario', 'industria'],
            impactosSectores: { construccion: -10, infraestructura: -7, inmobiliario: -6, industria: -5 },
            materiasPrimas: { acero: 12, cobre: 10, cemento: 9 },
            noticia: 'Los retrasos de suministro provocan un fuerte aumento en el precio de materiales.',
            alerta: '🧱 La construcción se ve presionada por la escasez.',
            etiquetas: ['materiales', 'construccion', 'suministro']
        },
        {
            id: 'sequia_severa',
            titulo: '⛈️ Sequía severa',
            subtitulo: 'La producción agrícola cae.',
            descripcion: 'Una temporada de sequía reduce las cosechas y genera presión sobre los precios alimentarios.',
            categoria: 'ambiental',
            rareza: 'raro',
            intensidad: 'extrema',
            duracion: 170,
            cooldown: 500,
            probabilidad: 2,
            sectoresBeneficiados: [],
            sectoresPerjudicados: ['agricultura', 'alimentos', 'transporte'],
            impactosSectores: { agricultura: -15, alimentos: -8, transporte: -4 },
            materiasPrimas: { alimentos: 14, agua: 12 },
            liquidez: -7,
            volatilidad: 16,
            confianza: -9,
            noticia: 'Una temporada de sequía reduce las cosechas y genera presión sobre los precios alimentarios.',
            alerta: '⛈️ El campo se resiente y los alimentos suben.',
            etiquetas: ['clima', 'agricultura', 'alimentos']
        },
        {
            id: 'retiro_vehiculos',
            titulo: '🔧 Retiro masivo',
            subtitulo: 'Un fabricante suspende temporalmente las ventas.',
            descripcion: 'Un importante fabricante suspende entregas después de detectar un problema técnico.',
            categoria: 'empresa',
            rareza: 'poco_comun',
            intensidad: 'alta',
            duracion: 100,
            cooldown: 250,
            probabilidad: 6,
            sectoresBeneficiados: ['competidores_directos'],
            sectoresPerjudicados: ['automoviles', 'automoviles_electricos', 'proveedores'],
            impactosSectores: { automoviles: -6, automoviles_electricos: -5, proveedores: -4 },
            empresas: { beneficiadas: ['competidores_directos'], perjudicadas: ['empresa_afectada'] },
            liquidez: -4,
            volatilidad: 13,
            confianza: -8,
            noticia: 'Un importante fabricante suspende entregas después de detectar un problema técnico.',
            alerta: '🔧 Un fabricante clave se ve obligado a retirar oferta.',
            etiquetas: ['automoviles', 'retirada', 'fabricante']
        },
        {
            id: 'ciberataque_global',
            titulo: '🔐 Ciberataque global',
            subtitulo: 'Varias redes empresariales sufren interrupciones.',
            descripcion: 'Una interrupción digital afecta a múltiples empresas y dispara la demanda de servicios de ciberseguridad.',
            categoria: 'crisis',
            rareza: 'raro',
            intensidad: 'extrema',
            duracion: 100,
            cooldown: 450,
            probabilidad: 2,
            sectoresBeneficiados: ['ciberseguridad'],
            sectoresPerjudicados: ['tecnologia', 'finanzas', 'ecommerce', 'telecomunicaciones'],
            impactosSectores: { ciberseguridad: 17, tecnologia: 5, finanzas: -8, ecommerce: -7, telecomunicaciones: -6 },
            bancos: { efecto: 'refuerzan seguridad y restringen operaciones temporalmente', tasa: 4, aprobacion: -6, limite: -5 },
            liquidez: -8,
            volatilidad: 18,
            confianza: -12,
            eventosRelacionados: ['boom_ciberseguridad'],
            noticia: 'Una interrupción digital afecta a múltiples empresas y dispara la demanda de servicios de ciberseguridad.',
            alerta: '🔐 La seguridad digital pasa a ser prioridad inmediata.',
            etiquetas: ['ciberseguridad', 'tecnologia', 'riesgo']
        },
        {
            id: 'fuga_capital',
            titulo: '📉 Fuga de capital',
            subtitulo: 'Los inversores buscan activos considerados más seguros.',
            descripcion: 'Los inversores reducen exposición a activos de mayor riesgo.',
            categoria: 'financiero',
            rareza: 'raro',
            intensidad: 'alta',
            duracion: 130,
            cooldown: 400,
            probabilidad: 3,
            sectoresBeneficiados: [],
            sectoresPerjudicados: ['finanzas', 'inmobiliario', 'empresas_riesgo'],
            impactosSectores: { finanzas: -10, inmobiliario: -8, empresas_riesgo: -12 },
            bancos: { efecto: 'reducen exposición a clientes riesgosos', tasa: 6, aprobacion: -10, limite: -10 },
            liquidez: -12,
            volatilidad: 16,
            confianza: -13,
            noticia: 'Los inversores reducen exposición a activos de mayor riesgo.',
            alerta: '📉 El mercado empieza a huir de activos volátiles.',
            etiquetas: ['finanzas', 'capital', 'riesgo']
        },
        {
            id: 'crisis_energetica',
            titulo: '⛽ Crisis energética',
            subtitulo: 'La oferta energética se reduce inesperadamente.',
            descripcion: 'Una interrupción de suministro provoca un fuerte aumento de los precios energéticos.',
            categoria: 'crisis',
            rareza: 'raro',
            intensidad: 'extrema',
            duracion: 160,
            cooldown: 450,
            probabilidad: 3,
            sectoresBeneficiados: ['petroleo', 'gas', 'energia'],
            sectoresPerjudicados: ['transporte', 'aerolineas', 'industria', 'turismo'],
            impactosSectores: { petroleo: 15, gas: 13, energia: 10, transporte: -8, aerolineas: -10, industria: -7, turismo: -5 },
            materiasPrimas: { petroleo: 18, gas: 15 },
            bancos: { efecto: 'aumentan riesgo para empresas intensivas en energía', tasa: 4, aprobacion: -5, limite: -6 },
            liquidez: -9,
            volatilidad: 18,
            confianza: -12,
            noticia: 'Una interrupción de suministro provoca un fuerte aumento de los precios energéticos.',
            alerta: '⛽ La energía vuelve a convertirse en una variable crítica.',
            etiquetas: ['energia', 'petroleo', 'crisis']
        },
        {
            id: 'colapso_inmobiliario',
            titulo: '🏘️ Colapso inmobiliario',
            subtitulo: 'El crédito caro frena la compra de viviendas.',
            descripcion: 'La actividad inmobiliaria se desploma después de un fuerte endurecimiento de las condiciones crediticias.',
            categoria: 'crisis',
            rareza: 'raro',
            intensidad: 'extrema',
            duracion: 180,
            cooldown: 550,
            probabilidad: 2,
            sectoresBeneficiados: [],
            sectoresPerjudicados: ['inmobiliario', 'construccion', 'materiales', 'finanzas'],
            impactosSectores: { inmobiliario: -15, construccion: -11, materiales: -7, finanzas: -8 },
            bancos: { efecto: 'reducen crédito inmobiliario', tasa: 9, aprobacion: -15, limite: -15 },
            creditos: { disponibles: ['refinanciacion'], modificadores: { refinanciacion: 6, adquisicion: 8 } },
            liquidez: -12,
            volatilidad: 18,
            confianza: -16,
            noticia: 'La actividad inmobiliaria se desploma después de un fuerte endurecimiento de las condiciones crediticias.',
            alerta: '🏘️ El inmobiliario entra en una fase de caida profunda.',
            etiquetas: ['inmobiliario', 'crédito', 'crisis']
        },
        {
            id: 'caida_redes',
            titulo: '📵 Caída de redes',
            subtitulo: 'Una interrupción afecta servicios digitales.',
            descripcion: 'Una interrupción generalizada deja temporalmente fuera de servicio múltiples plataformas digitales.',
            categoria: 'tecnologia',
            rareza: 'poco_comun',
            intensidad: 'alta',
            duracion: 70,
            cooldown: 220,
            probabilidad: 7,
            sectoresBeneficiados: ['ciberseguridad'],
            sectoresPerjudicados: ['telecomunicaciones', 'ecommerce', 'tecnologia'],
            impactosSectores: { telecomunicaciones: -9, ecommerce: -8, tecnologia: -5, ciberseguridad: 8 },
            liquidez: -4,
            volatilidad: 11,
            confianza: -7,
            noticia: 'Una interrupción generalizada deja temporalmente fuera de servicio múltiples plataformas digitales.',
            alerta: '📵 La conectividad digital se degrada temporalmente.',
            etiquetas: ['redes', 'digital', 'telecom']
        },
        {
            id: 'clima_extremo',
            titulo: '🌪️ Clima extremo',
            subtitulo: 'Fenómenos naturales afectan producción y transporte.',
            descripcion: 'Una serie de fenómenos climáticos provoca interrupciones en varias cadenas de suministro.',
            categoria: 'ambiental',
            rareza: 'raro',
            intensidad: 'extrema',
            duracion: 130,
            cooldown: 400,
            probabilidad: 3,
            sectoresBeneficiados: ['seguros'],
            sectoresPerjudicados: ['agricultura', 'transporte', 'construccion', 'turismo'],
            impactosSectores: { agricultura: -9, transporte: -8, construccion: -7, seguros: 10, turismo: -6 },
            liquidez: -7,
            volatilidad: 15,
            confianza: -10,
            noticia: 'Una serie de fenómenos climáticos provoca interrupciones en varias cadenas de suministro.',
            alerta: '🌪️ El clima extremo empieza a golpear la actividad económica.',
            etiquetas: ['clima', 'seguros', 'transporte']
        },
        {
            id: 'escalada_industrial',
            titulo: '🏭 Escalada industrial',
            subtitulo: 'La producción industrial aumenta más de lo esperado.',
            descripcion: 'La producción industrial acelera y la actividad fabril se fortalece.',
            categoria: 'boom',
            rareza: 'comun',
            intensidad: 'alta',
            duracion: 100,
            cooldown: 240,
            probabilidad: 10,
            sectoresBeneficiados: ['industria', 'maquinaria', 'acero', 'transporte', 'energia'],
            sectoresPerjudicados: [],
            impactosSectores: { industria: 12, maquinaria: 10, acero: 7, transporte: 6, energia: 5 },
            liquidez: 4,
            volatilidad: 6,
            confianza: 7,
            noticia: 'La producción industrial supera las previsiones y acelera el crecimiento.',
            alerta: '🏭 La industria se reactivó y el sistema gana velocidad.',
            etiquetas: ['industria', 'produccion', 'maquinaria']
        },
        {
            id: 'automatizacion_industrial',
            titulo: '🤖 Automatización industrial',
            subtitulo: 'Una nueva generación de robots aumenta la productividad de las fábricas.',
            descripcion: 'Los robots se convierten en un motor de eficiencia industrial y productividad.',
            categoria: 'tecnologia',
            rareza: 'raro',
            intensidad: 'alta',
            duracion: 130,
            cooldown: 300,
            probabilidad: 3,
            sectoresBeneficiados: ['robotica', 'industria', 'software_industrial', 'maquinaria'],
            sectoresPerjudicados: ['manufactura_tradicional'],
            impactosSectores: { robotica: 15, industria: 9, software_industrial: 10, maquinaria: 8, manufactura_tradicional: -4 },
            liquidez: 3,
            volatilidad: 8,
            confianza: 7,
            noticia: 'Una nueva generación de robots mejora la productividad de las fábricas.',
            alerta: '🤖 La automatización gana fuerza y redefine la industria.',
            etiquetas: ['robotica', 'industria', 'automatizacion']
        },
        {
            id: 'computacion_nueva_generacion',
            titulo: '🧠 Computación de nueva generación',
            subtitulo: 'Una arquitectura informática aumenta radicalmente la capacidad de procesamiento.',
            descripcion: 'Los centros de datos y la computación intensiva reciben un gran impulso.',
            categoria: 'tecnologia',
            rareza: 'epico',
            intensidad: 'extrema',
            duracion: 150,
            cooldown: 450,
            probabilidad: 1.5,
            sectoresBeneficiados: ['tecnologia', 'semiconductores', 'IA', 'centros_datos'],
            sectoresPerjudicados: [],
            impactosSectores: { tecnologia: 13, semiconductores: 16, IA: 12, centros_datos: 10 },
            liquidez: 5,
            volatilidad: 14,
            confianza: 10,
            noticia: 'Una arquitectura informática aumenta radicalmente la capacidad de procesamiento.',
            alerta: '🧠 La capacidad computacional se dispara y el mercado reacciona.',
            etiquetas: ['computacion', 'IA', 'semiconductores']
        },
        {
            id: 'descubrimiento_biotecnologico',
            titulo: '🧬 Descubrimiento biotecnológico',
            subtitulo: 'Una empresa descubre una nueva plataforma para desarrollar tratamientos más rápidamente.',
            descripcion: 'La biotecnología recibe un impulso importante con una nueva plataforma de desarrollo.',
            categoria: 'boom',
            rareza: 'epico',
            intensidad: 'extrema',
            duracion: 150,
            cooldown: 500,
            probabilidad: 1.5,
            sectoresBeneficiados: ['biotecnologia', 'farmaceuticas', 'salud'],
            sectoresPerjudicados: [],
            impactosSectores: { biotecnologia: 18, farmaceuticas: 12, salud: 8 },
            liquidez: 4,
            volatilidad: 12,
            confianza: 9,
            noticia: 'Una empresa descubre una nueva plataforma para desarrollar tratamientos más rápidamente.',
            alerta: '🧬 La biotecnología promete una nueva etapa de innovación.',
            etiquetas: ['biotecnologia', 'salud', 'farmaceuticas']
        },
        {
            id: 'crisis_logistica',
            titulo: '📦 Crisis logística',
            subtitulo: 'Los principales centros de distribución sufren retrasos.',
            descripcion: 'Los centros de distribución sufren retrasos y los clientes esperan más tiempo.',
            categoria: 'crisis',
            rareza: 'poco_comun',
            intensidad: 'alta',
            duracion: 120,
            cooldown: 270,
            probabilidad: 5,
            sectoresBeneficiados: [],
            sectoresPerjudicados: ['logistica', 'transporte', 'comercio', 'industria'],
            impactosSectores: { logistica: -12, transporte: -9, comercio: -7, industria: -6 },
            materiasPrimas: { combustible: 7 },
            liquidez: -4,
            volatilidad: 11,
            confianza: -6,
            noticia: 'Los principales centros de distribución sufren retrasos y el mercado ajusta sus expectativas.',
            alerta: '📦 La logística se vuelve un cuello de botella operativo.',
            etiquetas: ['logistica', 'transporte', 'comercio']
        },
        {
            id: 'boom_transporte',
            titulo: '🚢 Boom del transporte',
            subtitulo: 'El comercio internacional aumenta y necesita ampliar capacidad.',
            descripcion: 'El comercio internacional gana fuerza y exige más capacidad logística.',
            categoria: 'boom',
            rareza: 'comun',
            intensidad: 'alta',
            duracion: 120,
            cooldown: 260,
            probabilidad: 7,
            sectoresBeneficiados: ['transporte', 'logistica', 'puertos', 'comercio'],
            sectoresPerjudicados: [],
            impactosSectores: { transporte: 10, logistica: 14, puertos: 12, comercio: 8 },
            liquidez: 4,
            volatilidad: 7,
            confianza: 8,
            noticia: 'El comercio internacional aumenta y las empresas necesitan ampliar rápidamente su capacidad logística.',
            alerta: '🚢 El transporte internacional entra en una fase de expansión.',
            etiquetas: ['transporte', 'logistica', 'comercio']
        },
        {
            id: 'credito_barato',
            titulo: '💳 Crédito barato',
            subtitulo: 'Los bancos compiten agresivamente por nuevos clientes.',
            descripcion: 'Los bancos aumentan la disposición a prestar y se intensifica la competencia por clientes.',
            categoria: 'financiero',
            rareza: 'comun',
            intensidad: 'alta',
            duracion: 150,
            cooldown: 300,
            probabilidad: 8,
            sectoresBeneficiados: ['inmobiliario', 'construccion', 'empresas', 'consumo'],
            sectoresPerjudicados: [],
            impactosSectores: { inmuebles: 5, construccion: 5, empresas: 4, consumo: 4 },
            bancos: { efecto: 'más oferta de financiación', tasa: -10, aprobacion: 15, limite: 12 },
            creditos: { disponibles: ['puente', 'expansion', 'adquisicion', 'refinanciacion', 'oportunidad'], modificadores: { puente: -5, expansion: -7, adquisicion: -5, refinanciacion: -8, oportunidad: -6 } },
            liquidez: 6,
            volatilidad: 5,
            confianza: 10,
            noticia: 'Los bancos compiten agresivamente por captar nuevos clientes.',
            alerta: '💳 El crédito vuelve a estar más accesible para empresas y hogares.',
            etiquetas: ['crédito', 'bancos', 'financiacion']
        },
        {
            id: 'restriccion_crediticia',
            titulo: '🚫 Restricción crediticia',
            subtitulo: 'Los bancos reducen el riesgo y endurecen los requisitos.',
            descripcion: 'La financiación se endurece y las decisiones de financiación se vuelven más estrictas.',
            categoria: 'financiero',
            rareza: 'poco_comun',
            intensidad: 'alta',
            duracion: 150,
            cooldown: 330,
            probabilidad: 6,
            sectoresBeneficiados: [],
            sectoresPerjudicados: ['empresas', 'inmobiliario', 'construccion'],
            impactosSectores: { empresas: -8, inmobiliario: -10, construccion: -8 },
            bancos: { efecto: 'endurecen condiciones', tasa: 9, aprobacion: -15, limite: -12 },
            creditos: { disponibles: ['adquisicion', 'expansion'], modificadores: { adquisicion: 10, expansion: 8 } },
            liquidez: -8,
            volatilidad: 9,
            confianza: -8,
            noticia: 'Los bancos reducen el riesgo y endurecen los requisitos para conceder crédito.',
            alerta: '🚫 La financiación se hace más dura y los riesgos suben.',
            etiquetas: ['crédito', 'bancos', 'restriccion']
        },
        {
            id: 'guerra_bancos',
            titulo: '🏦 Guerra de bancos',
            subtitulo: 'Los bancos compiten por captar a los mejores clientes.',
            descripcion: 'Los bancos lanzan ofertas especiales para atraer a clientes con buen score.',
            categoria: 'financiero',
            rareza: 'poco_comun',
            intensidad: 'alta',
            duracion: 120,
            cooldown: 300,
            probabilidad: 5,
            sectoresBeneficiados: ['finanzas', 'empresas', 'consumo'],
            sectoresPerjudicados: [],
            impactosSectores: { finanzas: 8, empresas: 6, consumo: 5 },
            bancos: { efecto: 'compiten por clientes', tasa: -7, aprobacion: 10, limite: 8 },
            liquidez: 5,
            volatilidad: 4,
            confianza: 9,
            noticia: 'Varios bancos compiten por captar nuevos clientes con ofertas más atractivas.',
            alerta: '🏦 La competencia bancaria se dispara y mejora las condiciones.',
            etiquetas: ['bancos', 'competencia', 'crédito']
        },
        {
            id: 'crisis_liquidez',
            titulo: '🚨 Crisis de liquidez',
            subtitulo: 'Los bancos comienzan a conservar efectivo.',
            descripcion: 'La liquidez se reduce y los nuevos préstamos se vuelven más difíciles de obtener.',
            categoria: 'crisis',
            rareza: 'raro',
            intensidad: 'alta',
            duracion: 140,
            cooldown: 360,
            probabilidad: 4,
            sectoresBeneficiados: [],
            sectoresPerjudicados: ['finanzas', 'empresas', 'inmobiliario'],
            impactosSectores: { finanzas: -15, empresas: -10, inmobiliario: -9 },
            bancos: { efecto: 'reducen nuevos préstamos', tasa: 10, aprobacion: -18, limite: -15 },
            creditos: { disponibles: ['credito_emergencia'], modificadores: { credito_emergencia: -2 } },
            liquidez: -20,
            volatilidad: 14,
            confianza: -12,
            noticia: 'Los bancos comienzan a conservar efectivo y reducen las nuevas operaciones de crédito.',
            alerta: '🚨 La liquidez bancaria se mueve en una dirección defensiva.',
            etiquetas: ['liquidez', 'bancos', 'crisis']
        },
        {
            id: 'bonificacion_historial',
            titulo: '⭐ Bonificación por historial',
            subtitulo: 'Los bancos premian a jugadores con buen score.',
            descripcion: 'Los bancos ofrecen condiciones especiales a quienes tienen un historial sólido de pagos.',
            categoria: 'financiero',
            rareza: 'poco_comun',
            intensidad: 'alta',
            duracion: 180,
            cooldown: 360,
            probabilidad: 5,
            sectoresBeneficiados: ['finanzas', 'empresas', 'consumo'],
            sectoresPerjudicados: [],
            impactosSectores: { finanzas: 6, empresas: 4, consumo: 4 },
            bancos: { efecto: 'premian customers con historial sólido', tasa: -8, aprobacion: 15, limite: 10 },
            liquidez: 3,
            volatilidad: 2,
            confianza: 8,
            noticia: 'Los bancos empiezan a premiar a los jugadores con excelente historial.',
            alerta: '⭐ Las mejores historias crediticias reciben apuestas más favorables.',
            etiquetas: ['bancos', 'score', 'historial']
        },
        {
            id: 'nuevo_corredor_comercial',
            titulo: '🌎 Nuevo corredor comercial',
            subtitulo: 'Se abre una nueva ruta internacional.',
            descripcion: 'Una nueva ruta internacional reduce tiempos de transporte y mejora los flujos comerciales.',
            categoria: 'geopolitico',
            rareza: 'poco_comun',
            intensidad: 'alta',
            duracion: 140,
            cooldown: 300,
            probabilidad: 6,
            sectoresBeneficiados: ['comercio', 'logistica', 'transporte', 'exportaciones'],
            sectoresPerjudicados: [],
            impactosSectores: { comercio: 9, logistica: 12, transporte: 10, exportaciones: 8 },
            liquidez: 4,
            volatilidad: 3,
            confianza: 8,
            noticia: 'Se abre una nueva ruta internacional que reduce tiempos de transporte.',
            alerta: '🌎 El comercio global gana un nuevo corredor de velocidad.',
            etiquetas: ['comercio', 'rutas', 'logistica']
        },
        {
            id: 'nuevos_aranceles',
            titulo: '🧾 Nuevos aranceles',
            subtitulo: 'Los costos de importación aumentan.',
            descripcion: 'Un cambio arancelario reduce la competitividad de algunas importaciones y favorece producción local.',
            categoria: 'geopolitico',
            rareza: 'poco_comun',
            intensidad: 'alta',
            duracion: 130,
            cooldown: 320,
            probabilidad: 6,
            sectoresBeneficiados: ['produccion_nacional'],
            sectoresPerjudicados: ['importadores', 'comercio', 'industria'],
            impactosSectores: { importadores: -9, comercio: -6, industria: -5, produccion_nacional: 6 },
            liquidez: -3,
            volatilidad: 8,
            confianza: -4,
            noticia: 'Se incrementan los costos de importación y se mueve el equilibrio comercial.',
            alerta: '🧾 Los aranceles cambian el peso relativo de comercio e industria.',
            etiquetas: ['aranceles', 'comercio', 'industria']
        },
        {
            id: 'restriccion_exportaciones',
            titulo: '🚢 Restricción de exportaciones',
            subtitulo: 'Un gran productor limita temporalmente la exportación.',
            descripcion: 'La oferta de una materia prima clave se restringe y el mercado reacciona.',
            categoria: 'geopolitico',
            rareza: 'poco_comun',
            intensidad: 'alta',
            duracion: 120,
            cooldown: 260,
            probabilidad: 5,
            sectoresBeneficiados: ['productores_alternativos'],
            sectoresPerjudicados: ['empresas_dependientes'],
            impactosSectores: { materia_prima: 17, empresas_dependientes: -9, productores_alternativos: 8 },
            liquidez: -3,
            volatilidad: 10,
            confianza: -5,
            noticia: 'Un gran productor limita temporalmente la exportación de una materia prima.',
            alerta: '🚢 La limitada oferta de materia prima empieza a mover precios.',
            etiquetas: ['exportaciones', 'materia_prima', 'geopolítica']
        },
        {
            id: 'acuerdo_energetico',
            titulo: '⚡ Acuerdo energético',
            subtitulo: 'Varios países firman acuerdos de suministro energético de largo plazo.',
            descripcion: 'El mercado recibe una señal favorable para energía, industria y transporte.',
            categoria: 'geopolitico',
            rareza: 'poco_comun',
            intensidad: 'alta',
            duracion: 160,
            cooldown: 350,
            probabilidad: 5,
            sectoresBeneficiados: ['energia', 'industria', 'transporte'],
            sectoresPerjudicados: [],
            impactosSectores: { energia: 6, industria: 5, transporte: 4 },
            liquidez: 3,
            volatilidad: -10,
            confianza: 8,
            noticia: 'Varios países firman acuerdos de suministro energético de largo plazo.',
            alerta: '⚡ La energía gana previsibilidad y estabilidad.',
            etiquetas: ['energia', 'geopolítica', 'suministro']
        },
        {
            id: 'ola_calor',
            titulo: '🌡️ Onda de calor',
            subtitulo: 'Las temperaturas extremas disparan la demanda de electricidad.',
            descripcion: 'La demanda eléctrica sube y algunas actividades productivas se ven afectadas.',
            categoria: 'ambiental',
            rareza: 'comun',
            intensidad: 'alta',
            duracion: 100,
            cooldown: 230,
            probabilidad: 8,
            sectoresBeneficiados: ['energia', 'electricidad'],
            sectoresPerjudicados: ['agricultura', 'turismo'],
            impactosSectores: { energia: 10, electricidad: 8, agricultura: -6, turismo: -3 },
            liquidez: 2,
            volatilidad: 8,
            confianza: 4,
            noticia: 'Las temperaturas extremas disparan la demanda de electricidad.',
            alerta: '🌡️ La energía se vuelve más valiosa y costosa.',
            etiquetas: ['clima', 'energia', 'electricidad']
        },
        {
            id: 'inundaciones_industriales',
            titulo: '🌊 Inundaciones industriales',
            subtitulo: 'Una zona industrial importante reduce temporalmente su producción.',
            descripcion: 'Una zona industrial clave se ve afectada por inundaciones y reduce su capacidad operativa.',
            categoria: 'ambiental',
            rareza: 'poco_comun',
            intensidad: 'alta',
            duracion: 110,
            cooldown: 240,
            probabilidad: 6,
            sectoresBeneficiados: ['seguros'],
            sectoresPerjudicados: ['industria', 'logistica', 'construccion'],
            impactosSectores: { industria: -12, logistica: -9, construccion: -5, seguros: 10 },
            liquidez: -4,
            volatilidad: 11,
            confianza: -7,
            noticia: 'Una zona industrial importante reduce temporalmente su producción por inundaciones.',
            alerta: '🌊 El riesgo climático golpea el tejido productivo.',
            etiquetas: ['clima', 'industria', 'seguros']
        },
        {
            id: 'nueva_tecnologia_energetica',
            titulo: '🧪 Nueva tecnología energética',
            subtitulo: 'Una nueva tecnología mejora el almacenamiento de energía.',
            descripcion: 'Nuevos sistemas de almacenamiento mejoran la eficiencia del sector energético.',
            categoria: 'tecnologia',
            rareza: 'epico',
            intensidad: 'extrema',
            duracion: 150,
            cooldown: 450,
            probabilidad: 1.5,
            sectoresBeneficiados: ['baterias', 'renovables', 'vehiculos_electricos'],
            sectoresPerjudicados: ['petroleo'],
            impactosSectores: { baterias: 16, renovables: 12, vehiculos_electricos: 9, petroleo: -5 },
            liquidez: 5,
            volatilidad: 13,
            confianza: 9,
            noticia: 'Una nueva tecnología mejora significativamente el almacenamiento de energía.',
            alerta: '🧪 La energía será cada vez más flexible y eficiente.',
            etiquetas: ['energia', 'baterias', 'innovacion']
        },
        {
            id: 'revolucion_tecnologica_global',
            titulo: '💥 Revolución tecnológica global',
            subtitulo: 'Una innovación inesperada transforma varios sectores.',
            descripcion: 'Una tecnología inesperada cambia simultáneamente varios negocios y fomenta una nueva fase de innovación.',
            categoria: 'boom',
            rareza: 'legendario',
            intensidad: 'historica',
            duracion: 180,
            cooldown: 700,
            probabilidad: 0.25,
            sectoresBeneficiados: ['tecnologia', 'IA', 'industria', 'energia', 'robotica'],
            sectoresPerjudicados: ['empresas_obsoletas'],
            impactosSectores: { tecnologia: 20, IA: 18, industria: 12, energia: 8, robotica: 16, empresas_obsoletas: -18 },
            liquidez: 7,
            volatilidad: 20,
            confianza: 12,
            noticia: 'Una innovación inesperada transforma simultáneamente varios sectores.',
            alerta: '💥 La tecnología global da un salto histórico.',
            etiquetas: ['legendario', 'tecnologia', 'revolucion']
        },
        {
            id: 'crisis_financiera_global',
            titulo: '🌑 Crisis financiera global',
            subtitulo: 'La deuda, la liquidez y la confianza se deterioran a la vez.',
            descripcion: 'La combinación de problemas de deuda, liquidez y confianza provoca una caída generalizada.',
            categoria: 'crisis',
            rareza: 'legendario',
            intensidad: 'historica',
            duracion: 220,
            cooldown: 800,
            probabilidad: 0.25,
            sectoresBeneficiados: [],
            sectoresPerjudicados: ['finanzas', 'inmobiliario', 'tecnologia', 'industria', 'consumo'],
            impactosSectores: { finanzas: -18, inmobiliario: -15, tecnologia: -12, industria: -10, consumo: -8 },
            bancos: { efecto: 'reducen crédito y endurecen condiciones', tasa: 15, aprobacion: -20, limite: -20 },
            liquidez: -15,
            volatilidad: 25,
            confianza: -25,
            noticia: 'Una combinación de problemas de deuda, liquidez y confianza provoca una fuerte caída generalizada.',
            alerta: '🌑 La confianza financiera se rompe en varios mercados.',
            etiquetas: ['finanzas', 'legendario', 'crisis']
        },
        {
            id: 'descubrimiento_recurso_estrategico',
            titulo: '💎 Descubrimiento de recurso estratégico',
            subtitulo: 'Se encuentra una reserva extraordinaria de un recurso fundamental.',
            descripcion: 'El primer periodo aumenta la presión en el recurso, y después la oferta se normaliza y mejora el acceso para consumidores.',
            categoria: 'materias_primas',
            rareza: 'epico',
            intensidad: 'extrema',
            duracion: 180,
            cooldown: 550,
            probabilidad: 1.2,
            sectoresBeneficiados: ['mineria', 'consumidores_recurso'],
            sectoresPerjudicados: [],
            impactosSectores: { recurso: 25, mineria: 12 },
            materiasPrimas: { recurso: 25 },
            liquidez: 5,
            volatilidad: 14,
            confianza: 8,
            noticia: 'Se descubre un recurso estratégico que cambia el escenario mundial.',
            alerta: '💎 Un nuevo recurso aparece en el mapa de la economía global.',
            etiquetas: ['recurso', 'mineria', 'epico']
        },
        {
            id: 'boom_economico_mundial',
            titulo: '📈 Boom económico mundial',
            subtitulo: 'El crecimiento supera las expectativas y se acelera la inversión.',
            descripcion: 'El crecimiento global supera todas las expectativas, aumentando la actividad empresarial.',
            categoria: 'boom',
            rareza: 'epico',
            intensidad: 'alta',
            duracion: 180,
            cooldown: 500,
            probabilidad: 1.3,
            sectoresBeneficiados: ['industria', 'comercio', 'tecnologia', 'construccion', 'turismo', 'finanzas', 'consumo'],
            sectoresPerjudicados: [],
            impactosSectores: { industria: 12, comercio: 11, tecnologia: 9, construccion: 10, turismo: 9, consumo: 10, finanzas: 8 },
            bancos: { efecto: 'aumentan oferta de crédito', tasa: -6, aprobacion: 8, limite: 8 },
            liquidez: 6,
            volatilidad: 10,
            confianza: 12,
            noticia: 'El crecimiento supera todas las expectativas y aumenta la actividad empresarial global.',
            alerta: '📈 La economía global entra en una fase expansiva y eufórica.',
            etiquetas: ['boom', 'global', 'crecimiento']
        },
        {
            id: 'colapso_confianza',
            titulo: '😨 Colapso de confianza',
            subtitulo: 'Los inversores pierden rápidamente la confianza.',
            descripcion: 'Los inversores se retiran rápidamente de los mercados volátiles y la confianza se rompe.',
            categoria: 'crisis',
            rareza: 'legendario',
            intensidad: 'alta',
            duracion: 180,
            cooldown: 800,
            probabilidad: 0.25,
            sectoresBeneficiados: ['activos_defensivos'],
            sectoresPerjudicados: ['acciones', 'empresas_alto_riesgo', 'inmobiliario', 'tecnologia'],
            impactosSectores: { acciones: -15, empresas_alto_riesgo: -20, inmobiliario: -10, tecnologia: -12, activos_defensivos: 7 },
            bancos: { efecto: 'suben tasas y reducen aprobación', tasa: 8, aprobacion: -12, limite: 0 },
            liquidez: 10,
            volatilidad: 18,
            confianza: -18,
            noticia: 'Los inversores pierden rápidamente confianza en los mercados.',
            alerta: '😨 El miedo vuelve a dominar el mercado y el valor de la liquidez crece.',
            etiquetas: ['confianza', 'legendario', 'pánico']
        },
        {
            id: 'recuperacion_extraordinaria',
            titulo: '🔄 Recuperación extraordinaria',
            subtitulo: 'Los indicadores mejoran antes de lo esperado.',
            descripcion: 'Después de una crisis, los indicadores económicos comienzan a mejorar mucho antes de lo esperado.',
            categoria: 'boom',
            rareza: 'epico',
            intensidad: 'alta',
            duracion: 160,
            cooldown: 500,
            probabilidad: 1.5,
            sectoresBeneficiados: ['industria', 'construccion', 'consumo', 'tecnologia', 'comercio', 'finanzas'],
            sectoresPerjudicados: [],
            impactosSectores: { industria: 12, construccion: 10, consumo: 9, tecnologia: 8, comercio: 10, finanzas: 7 },
            liquidez: 5,
            volatilidad: 5,
            confianza: 10,
            noticia: 'Después de una crisis importante, los indicadores económicos comienzan a mejorar mucho antes de lo esperado.',
            alerta: '🔄 La recuperación llega con fuerza y da un nuevo impulso a la economía.',
            etiquetas: ['recuperacion', 'crisis', 'epico']
        }
    ];

    const INTENSIDAD_MAP = {
        leve: 0.5,
        moderada: 0.75,
        alta: 1,
        extrema: 1.5,
        historica: 2
    };

    class EventEngine {
        constructor(eventos = []) {
            this.eventos = eventos;
            this.activos = [];
            this.ultimos = [];
        }

        calcularProbabilidad(evento) {
            const probabilidadBase = Number(evento.probabilidad || 0);
            const intensidad = INTENSIDAD_MAP[evento.intensidad] || 1;
            return Math.min(0.45, (probabilidadBase / 100) * intensidad);
        }

        estaDisponible(evento) {
            const ahora = Date.now();
            const ventana = (Number(evento.cooldown || 0) || 0) * 1000;
            return !this.ultimos.some(item => item.id === evento.id && (ahora - item.at) < ventana);
        }

        generarEvento() {
            const disponibles = this.eventos.filter(evento => this.estaDisponible(evento));
            if (!disponibles.length) return null;

            const total = disponibles.reduce((acc, evento) => acc + Math.max(0.01, this.calcularProbabilidad(evento)), 0);
            let recorrido = Math.random() * total;

            for (const evento of disponibles) {
                recorrido -= Math.max(0.01, this.calcularProbabilidad(evento));
                if (recorrido <= 0) {
                    return evento;
                }
            }
            return disponibles[0];
        }

        activarEvento(evento) {
            const eventoNormalizado = {
                ...evento,
                id: evento.id,
                restante: Number(evento.duracion || 60),
                duracion: Number(evento.duracion || 60),
                activoDesde: Date.now(),
                tipo: evento.categoria === 'boom' ? 'boom' : 'crisis'
            };

            this.activos.push(eventoNormalizado);
            this.aplicarImpactos(eventoNormalizado);
            return eventoNormalizado;
        }

        aplicarImpactos(evento) {
            if (!window.sectorBoost) {
                window.sectorBoost = {};
            }

            Object.keys(window.sectorBoost).forEach(key => {
                window.sectorBoost[key] = 1;
            });

            if (evento.impactosSectores) {
                Object.entries(evento.impactosSectores).forEach(([sector, valor]) => {
                    const factor = 1 + Number(valor || 0) / 100;
                    window.sectorBoost[sector] = Math.max(0.5, Math.min(1.8, factor));
                });
            }
        }

        finalizarEvento(evento) {
            if (!evento || !evento.id) return;
            this.activos = this.activos.filter(item => item.id !== evento.id);
            this.ultimos.push({ id: evento.id, at: Date.now() });
            if (window.sectorBoost) {
                Object.keys(window.sectorBoost).forEach(key => {
                    window.sectorBoost[key] = 1;
                });
            }
        }

        toLegacyEvento(evento) {
            const sectores = [...new Set([...(evento.sectoresBeneficiados || []), ...(evento.sectoresPerjudicados || [])])];
            return {
                id: evento.id,
                titulo: evento.titulo,
                subtitulo: evento.subtitulo,
                descripcion: evento.descripcion,
                m: `${evento.titulo}${evento.subtitulo ? ` — ${evento.subtitulo}` : ''}`,
                categoria: evento.categoria,
                rareza: evento.rareza,
                intensidad: evento.intensidad,
                tipo: evento.categoria === 'boom' ? 'boom' : 'crisis',
                duracion: Number(evento.duracion || 60),
                cooldown: Number(evento.cooldown || 0),
                impacto: evento.impactosSectores || {},
                cats: sectores,
                noticias: evento.noticia || '',
                alerta: evento.alerta || '',
                impactosSectores: evento.impactosSectores || {},
                materiasPrimas: evento.materiasPrimas || {},
                bancos: evento.bancos || {},
                creditos: evento.creditos || {},
                liquidez: evento.liquidez || 0,
                volatilidad: evento.volatilidad || 0,
                confianza: evento.confianza || 0,
                efectosSecundarios: evento.efectosSecundarios || [],
                condiciones: evento.condiciones || [],
                eventosRelacionados: evento.eventosRelacionados || [],
                noticia: evento.noticia || '',
                etiquetas: evento.etiquetas || []
            };
        }
    }

    window.EVENTOS_COMPLETOS = EVENTOS_COMPLETOS;
    window.EventEngine = EventEngine;
    window.eventEngine = new EventEngine(EVENTOS_COMPLETOS);
})();
